### PR TITLE
Refactor tests, update readme, and add CI

### PR DESCRIPTION
**Pull request by jbytecode**
- Tests are separated using testset macros
- README.md updated with installation instructions
- Github action added for auto-testing (CI)

### CODE REVIEW

**Comment by jbytecode** [comment]
@ararslan - sorry for sending this PR, the repo was inactive for a while and I have just realized that you have come back again with new issues. If these are irrelevant and unnecessary, do not hesitate to ignore. 

thank you in advance.

**Comment by ararslan** [comment]
> sorry for sending this PR

No apologies necessary! I always welcome PRs and I appreciate your willingness to contribute. 🙂

> the repo was inactive for a while and I have just realized that you have come back again with new issues

Indeed, I got a notification earlier that someone has starred this repository, which reminded me that it exists. I took a look a look through it and I identified some things I'd like to do differently now (the code has changed very, very little since I wrote it in 2016).

> If these are irrelevant and unnecessary, do not hesitate to ignore.

Looks like I beat you to the switch to GitHub Actions for CI but the rest of the PR seems worthwhile! Can you remove the `.github/workflows/test.yml` added here? That's now redundant with a file on `master`.

**Comment by jbytecode** [comment]
@ararslan - how about that?

**Comment by jbytecode** [comment]
@ararslan - I want to integrate the Jackknife estimator in [Sqlite3Stats](https://github.com/jbytecode/Sqlite3Stats.jl).
Please ping me when you have done with it with a stable release.

:) btw, thank you for filling this gap in Julia!

**Comment by jbytecode** [comment]
@ararslan - I have removed the CI thingies. Please tell me if anything is required in my side.

**Comment by ararslan** [comment]
I pushed a couple of pedantic changes to your branch that I didn't want to bother you by asking you to make and all's well now. Thanks again for the contribution!

**Pull request merged**
